# Generated by Django 5.0.2 on 2024-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=400, verbose_name='Электронная почта')),
                ('avatar', models.CharField(max_length=40000, verbose_name='Аватар')),
                ('password', models.CharField(max_length=400, verbose_name='Пароль')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя пользователя')),
                ('user_info', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Информация о пользователе')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер пользователя')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужик'), ('female', 'Женщина')], max_length=400, null=True, verbose_name='Пол пользователя')),
            ],
        ),
    ]
